# Credits: https://github.com/getOtterWise/bash-uploader/issues/1

name: Run tests
 
on: [push]
 
jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
    
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install JS dependencies
        run: yarn install
 
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: xdebug   # can be switched with "pcov"
 
      - name: Run composer install
        run: composer install -n --prefer-dist
 
      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Yarn build
        run: yarn build
       
      - name: Execute tests
        run: vendor/bin/pest --coverage-clover=build/logs/clover.xml

      - name: Trigger forge deployment
        run: curl -X GET https://forge.laravel.com/servers/[...]
        
      - name: Calculate type coverage
        run: vendor/bin/pest --type-coverage --type-coverage-json=pest-coverage.json

      - name: Upload Coverage
        env:
          OTTERWISE_TOKEN: ${{ secrets.OTTERWISE_TOKEN }}
        run: bash <(curl -s https://raw.githubusercontent.com/getOtterWise/bash-uploader/main/uploader.sh) --type-coverage-file=pest-coverage.json
